# Import Libraries

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error,r2_score

import os
for dirname, _, filenames in os.walk('./archive/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import warnings
warnings.filterwarnings('ignore')

./archive/NFLX.csv

# Data Loading

In [30]:
df = pd.read_csv("../../data/stock_price_prediction_netflix/NFLX.csv")

In [31]:
df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2018-02-05,262.000000,267.899994,250.029999,254.259995,254.259995,11896100
1,2018-02-06,247.699997,266.700012,245.000000,265.720001,265.720001,12595800
2,2018-02-07,266.579987,272.450012,264.329987,264.559998,264.559998,8981500
3,2018-02-08,267.079987,267.619995,250.000000,250.100006,250.100006,9306700
4,2018-02-09,253.850006,255.800003,236.110001,249.470001,249.470001,16906900
5,2018-02-12,252.139999,259.149994,249.000000,257.950012,257.950012,8534900
6,2018-02-13,257.290009,261.410004,254.699997,258.269989,258.269989,6855200
7,2018-02-14,260.470001,269.880005,260.329987,266.000000,266.000000,10972000
8,2018-02-15,270.029999,280.500000,267.630005,280.269989,280.269989,10759700
9,2018-02-16,278.730011,281.959991,275.690002,278.519989,278.519989,8312400

In [32]:
viz = df.copy()

# Data Preparation

In [33]:
df.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [34]:
df.shape

(1009, 7)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1009 entries, 0 to 1008
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1009 non-null   object
 1   Open       1009 non-null   float64
 2   High       1009 non-null   float64
 3   Low        1009 non-null   float64
 4   Close      1009 non-null   float64
 5   Adj Close  1009 non-null   float64
 6   Volume     1009 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 55.3+ KB

In [36]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Open,1009.0,4.190597e+02,1.085375e+02,2.339200e+02,3.314900e+02,3.777700e+02,5.091300e+02,6.923500e+02
High,1009.0,4.253207e+02,1.092630e+02,2.506500e+02,3.363000e+02,3.830100e+02,5.156300e+02,7.009900e+02
Low,1009.0,4.123740e+02,1.075559e+02,2.312300e+02,3.260000e+02,3.708800e+02,5.025300e+02,6.860900e+02
Close,1009.0,4.190007e+02,1.082900e+02,2.338800e+02,3.316200e+02,3.786700e+02,5.090800e+02,6.916900e+02
Adj Close,1009.0,4.190007e+02,1.082900e+02,2.338800e+02,3.316200e+02,3.786700e+02,5.090800e+02,6.916900e+02
Volume,1009.0,7.570685e+06,5.465535e+06,1.144000e+06,4.091900e+06,5.934500e+06,9.322400e+06,5.890430e+07

In [37]:
train, test = train_test_split(df, test_size = 0.2)

In [38]:
test_pred = test.copy()

In [39]:
train.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
864,2021-07-13,535.760010,545.330017,535.760010,540.679993,540.679993,2751600
135,2018-08-17,319.010010,324.369995,312.959991,316.779999,316.779999,10407900
309,2019-04-30,369.559998,374.500000,368.350006,370.540009,370.540009,3870100
265,2019-02-26,362.980011,365.700012,359.329987,364.970001,364.970001,4944600
984,2021-12-31,610.010010,614.080017,602.049988,602.440002,602.440002,1995900
792,2021-03-30,510.510010,514.409973,506.910004,513.390015,513.390015,2418100
570,2020-05-12,442.000000,444.170013,431.359985,431.820007,431.820007,4598200
178,2018-10-18,360.670013,362.200012,346.049988,346.709991,346.709991,18461000
710,2020-11-30,490.079987,492.549988,481.269989,490.700012,490.700012,3530900
233,2019-01-09,317.709991,323.350006,313.500000,319.959991,319.959991,13343200

In [40]:
test.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume
562,2020-04-30,410.309998,424.440002,408.000000,419.850006,419.850006,7954000
290,2019-04-02,366.250000,368.420013,362.220001,367.720001,367.720001,5158700
514,2020-02-21,385.329987,387.320007,377.899994,380.070007,380.070007,3930100
506,2020-02-10,365.000000,374.799988,362.519989,371.070007,371.070007,5294100
634,2020-08-12,471.339996,482.489990,470.179993,475.470001,475.470001,5439200
629,2020-08-05,508.679993,510.100006,501.200012,502.109985,502.109985,4308200
1008,2022-02-04,407.309998,412.769989,396.640015,410.170013,410.170013,7782400
764,2021-02-18,549.000000,550.000000,538.229980,548.219971,548.219971,2456200
862,2021-07-09,531.000000,538.260010,528.580017,535.979980,535.979980,2777200
220,2018-12-19,269.959991,280.869995,263.769989,266.769989,266.769989,13788400

In [41]:
x_train = train[['Open', 'High', 'Low', 'Volume']].values
x_test = test[['Open', 'High', 'Low', 'Volume']].values

In [42]:
y_train = train['Close'].values
y_test = test['Close'].values

# Linear Regression

In [43]:
model_lnr = LinearRegression()
model_lnr.fit(x_train, y_train)

LinearRegression()